### PR TITLE
Support MiSeq V2 Micro

### PR DESCRIPTION
**Pull request by chuan-wang**
Talked with CN and HZ, and they decided that we take MiSeq V2 Micro as non-accredited and therefore no validation or verification is needed. /CW

### CODE REVIEW

**Review by alneberg — APPROVED** [review]
Looks good!

**Comment by aanil** [comment]
Does this require https://github.com/SciLifeLab/StatusDB_views/pull/184 be merged first?

**Comment by alneberg** [comment]
@aanil maybe not require, but things wont' show up without it. I approved that one as well now though.

**Review by aanil — APPROVED** [review]
👍

**Pull request merged**
