### PR TITLE
Add ToulligQC reports to ONT

### PR DESCRIPTION
**Pull request by kedhammar**
This will necessitate changing the settings.yaml as well as creating the dir /var/local/toulligqc_reports.

### CODE REVIEW

**Comment by kedhammar** [comment]
Linked to https://github.com/NationalGenomicsInfrastructure/TACA/pull/448

**Comment by alneberg** [comment]
I just sent a request to IT to create the directory `/var/local/other_reports` and then we can create `toulligqc` subdirectory inside that one ourselves. I guess this will need slight adjustment of your PRs, sorry!

**Review by alneberg — APPROVED** [review]
Looks good! Hold back on merging until the settings.yaml is updated though. Will you make a PR in ngi-git?

**Comment by kedhammar** [comment]
> I just sent a request to IT to create the directory `/var/local/other_reports` and then we can create `toulligqc` subdirectory inside that one ourselves. I guess this will need slight adjustment of your PRs, sorry!

I think the report dir is just in the configs, so both PRs are fine I think.

> Looks good! Hold back on merging until the settings.yaml is updated though. Will you make a PR in ngi-git?

Can do

**Comment by kedhammar** [comment]
Linked to https://ngi-git.scilifelab.se/NGI/conf/pulls/82

**Comment by kedhammar** [comment]
Linked to https://ngi-git.scilifelab.se/NGI/Documentation/pulls/37

**Pull request merged**
